name: "into-docker"
description: "Use the into-docker CLI tool to build a Docker image"
branding:
  icon: "terminal"
  color: "yellow"
inputs:
  version:
    description: "Version of the CLI tool"
    required: false
  builder:
    description: "Builder image to use"
    required: true
  image:
    description: 'Docker image to build (in the format "name:tag")'
    required: false
  source-path:
    description: "Path, relative to the project root, to use for the build"
    required: true
    default: "."
  artifacts-path:
    description: "Path to write the artifacts created in the build phase to."
    required: false
  cache-path:
    description: >
      Cache archive to create. If this file exists it will be used to provide
      cached files to the build.
    required: false
  platform:
    description: "Target platform to build for."
    required: false
  profile:
    description: "Build profile to use"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.version }}
    - ${{ inputs.builder }}
    - ${{ inputs.image }}
    - ${{ inputs.source-path }}
    - ${{ inputs.artifacts-path }}
    - ${{ inputs.cache-path }}
    - ${{ inputs.platform }}
    - ${{ inputs.profile }}
